### ISSUE TITLE
BC break in version 1.4.2

### ISSUE THREAD

**Issue by Wenkow** [sitmpcz/saml#3]
Usage of Nette\Application\LinkGenerator->requestToUrl() [1] is possible in nette/application 3.2 and higher. This breaks compatibility with older app stacks and ends in server error. Please fix needed dependencies or code

[1] https://github.com/sitmpcz/saml/blob/1ba30646b720bbf033aca15f13a5ca88e9547c42/src/Presenters/BaseSamlPresenter.php#L34C46-L34C58

**Comment by zabous** [comment]
I proposed a solution in version 1.4.3, but I don't have any project that uses the old version of nette/application. Could you please test it?

**Comment by Wenkow** [comment]
It's tested already, ending in Nette\MemberAccessException -> Call to undefined method Nette\Application\LinkGenerator::requestToUrl(). 

I've made a PR to fix dependecy and to avoid installation with older previous version of nette/application .

**Comment by Wenkow** [comment]
Tested, works fine
